name: Son Pham
markdown: redcarpet
pygments: true
permalink: pretty
url: https://s0nny.github.io
description: Son Pham's personal site.
timezone: US/Central
url:
    home: /
    posts: /posts
    projects: /code
    about: /about
    github: https://github.com/sonph
    linkedin: https://linkedin.com/in/sonph
    facebook: https://facebook.com/s0nnyftw
    tags: /tags
