name: Son Pham
markdown: redcarpet
pygments: true
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "autolink", "no_intra_emphasis"]

permalink: pretty
url: http://sonph.net
description: Son Pham's personal site.
keywords:
timezone: US/Central
link:
    home: /
    posts: /posts
    code: /code
    about: /about
    github: https://github.com/sonph
    linkedin: https://linkedin.com/in/sonph
    facebook: https://facebook.com/s0nnyftw
    tags: /tags
