name: Son Pham
markdown: redcarpet
pygments: true
permalink: pretty
url: https://sonph.net/
description: Son Pham's personal site.
keywords:
timezone: US/Central
link:
    home: /
    posts: /posts
    projects: /code
    about: /about
    github: https://github.com/sonph
    linkedin: https://linkedin.com/in/sonph
    facebook: https://facebook.com/s0nnyftw
    tags: /tags
